---
# General config.
#gitlab_domain: example.com
gitlab_domain: davydoffserge.ru
gitlab_external_url: "http://{{ gitlab_domain }}/"
gitlab_edition: "gitlab-ce"
gitlab_config_template: "gitlab.rb.j2"
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"
#gitlab_repository_installation_script_url:  "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/focal/gitlab-ce_15.2.0-ce.0_amd64.deb/download.deb"
gitlab_dependencies:
  - postfix
  - curl
  - tzdata

gitlab_time_zone: "UTC"
gitlab_default_theme: '3'

# GitLab root password after install
#gitlab_root_password: "{{ gitlab_psw }}"
gitlab_root_password: "{{ gitlab_psw }}"

# GitLab runner token after install
gitlab_runner_token: "*******"
