    
# Node List

[nginx]
nginx ansible_host=62.84.124.233

[db01]
db01 ansible_host=192.168.101.12

[db02]
db02 ansible_host=192.168.101.13

[app]
app ansible_host=192.168.101.14

[gitlab]
gitlab ansible_host=192.168.101.15

[runner]
runner ansible_host=192.168.101.16

[monitoring]
monitoring ansible_host=192.168.101.17

#

[myallhosts:children]
nginx
db01
db02
app
gitlab
runner
monitoring

[mydb:children]
db01
db02

#
    
[nginx:vars]
domain = "davydoffserge.ru"
le_staging = "true"

 [mydb:vars]
 replicator_psw = ""

[db01:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@62.84.124.233"'
mysql_replication_role = "master"

[db02:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@62.84.124.233"'
mysql_replication_role = "slave"

[app:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@62.84.124.233"'
domain = "davydoffserge.ru"

[gitlab:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@62.84.124.233"'
 gitlab_psw = ""
 gitlab_runner = ""
domain = "davydoffserge.ru"

[runner:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@62.84.124.233"'
 gitlab_runner = ""
domain = "davydoffserge.ru"

[monitoring:vars]
ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@62.84.124.233"'
 grafana_psw = 

[myallhosts:vars]
domain = "davydoffserge.ru"
ip_nginx = 192.168.100.11
ip_db01 = 192.168.101.12
ip_db02 = 192.168.101.13
ip_app = 192.168.101.14
ip_gitlab = 192.168.101.15
ip_runner = 192.168.101.16
ip_monitoring = 192.168.101.17

